///////////////////////////////////////////////////////////
//  CanData.cs
//  Implementation of the Class CanData
//  Generated by Enterprise Architect
//  Created on:      21-ËÄÔÂ-2016 11:39:30
//  Original author: lyc
///////////////////////////////////////////////////////////

namespace ModelLayer {
	public class CanData : MonitorData {

		public string dataField;
		public int dataLen;
		public bool externFlag;
		public int modelID;
		public bool remoteFlag;
		public bool sendRecv;

		public CanData(){

		}

		~CanData(){

		}

		public override void Dispose(){

		}

	}//end CanData

}//end namespace MySystem//end namespace MySystem