///////////////////////////////////////////////////////////
//  MonitorData.cs
//  Implementation of the Class MonitorData
//  Generated by Enterprise Architect
//  Created on:      21-ËÄÔÂ-2016 11:39:32
//  Original author: Administrator
///////////////////////////////////////////////////////////

namespace ModelLayer
{
	public class MonitorData {

		public double myValue;
		public string timeStamp;

		public MonitorData(){

		}

		~MonitorData(){

		}

		public virtual void Dispose(){

		}

	}//end MonitorData

}//end namespace MySystem//end namespace MySystem