///////////////////////////////////////////////////////////
//  MySystems.cs
//  Implementation of the Class MySystems
//  Generated by Enterprise Architect
//  Created on:      21-ËÄÔÂ-2016 11:39:33
//  Original author: lyc
///////////////////////////////////////////////////////////
using System.Collections.Generic;

namespace ModelLayer
{
	public class MySystems {

		public SystemOptions selectSystem;
		public int systemCount;
		public SystemOptions m_SystemOptions;


		public MySystems(){

		}

		~MySystems(){

		}

		public virtual void Dispose(){

		}

		public void changeSystem(){

		}

		/// 
		/// <param name="systems"></param>
		public void chooseSystem(List<SystemOptions> systems){

		}

		/// 
		/// <param name="user"></param>
		public List<SystemOptions> getSystems(Users user){

			return null;
		}

		public int init(){

			return 0;
		}

	}//end MySystems

}//end namespace MySystem//end namespace MySystem