///////////////////////////////////////////////////////////
//  Node.cs
//  Implementation of the Class Node
//  Generated by Enterprise Architect
//  Created on:      21-四月-2016 11:39:34
//  Original author: lyc
///////////////////////////////////////////////////////////
using System.Collections.Generic;

namespace ModelLayer
{
	public class Nodes {

        public int nodeID = -1;
        public string nodeName = "";
		public int chNO = -1;
		//public Nodes parent;
		public string signalType = "";
        public string device = "";

		public Nodes(){

		}

		~Nodes(){

		}

		public virtual void Dispose(){

		}

        public Dictionary<string, string[]> getNodeDic() 
        {
            Dictionary<string, string[]> dic = new Dictionary<string, string[]>();
            dic.Add("节点ID", new string[]{nodeID.ToString()});
            dic.Add("节点名称", new string[]{nodeName});
            dic.Add("设备名称", new string[]{device});
            dic.Add("信号类型", new string[]{signalType});
            if (chNO != -1)
            { dic.Add("通道号", new string[] { chNO.ToString() }); }
            else
            { dic.Add("通道号", new string[] { "" }); }
            return dic;
        }

	}//end Node

}//end namespace MySystem//end namespace MySystem