///////////////////////////////////////////////////////////
//  PermissionTypes.cs
//  Implementation of the Class PermissionTypes
//  Generated by Enterprise Architect
//  Created on:      18-四月-2016 11:01:42
//  Original author: lyc
///////////////////////////////////////////////////////////

namespace ModelLayer
{
	/// <summary>
	/// 权限的枚举类型
	/// </summary>
	public enum PermissionTypes : int {

		None = 0,
		UserManage = 1,
		Cfg7120 = 2,
		CfgRemoteModel = 4,
		CfgWlan = 8,
		SelectData = 16,
		InsertData = 32,
		DeleteData = 64,
        Default = 58,
		All = 127

	}//end PermissionTypes

}//end namespace MySystem//end namespace ClassModel//end namespace 逻辑模型