///////////////////////////////////////////////////////////
//  SystemOptions.cs
//  Implementation of the Class SystemOptions
//  Generated by Enterprise Architect
//  Created on:      21-ËÄÔÂ-2016 11:39:36
//  Original author: Administrator
///////////////////////////////////////////////////////////


namespace ModelLayer {
	public class SystemOptions {

		public string sysName;
		public string sysOptions;
		public int userID;
		public Nodes m_Node;

		public SystemOptions(){

		}

		~SystemOptions(){

		}

		public virtual void Dispose(){

		}

	}//end SystemOptions

}//end namespace MySystem//end namespace MySystem