///////////////////////////////////////////////////////////
//  WirelessData.cs
//  Implementation of the Class WirelessData
//  Generated by Enterprise Architect
//  Created on:      21-ËÄÔÂ-2016 11:39:38
//  Original author: lyc
///////////////////////////////////////////////////////////


namespace ModelLayer
{
	public class WirelessData : MonitorData {

		public WirelessData(){

		}

		~WirelessData(){

		}

		public override void Dispose(){

		}

	}//end WirelessData

}//end namespace MySystem//end namespace MySystem